Repository simple-lang/simple, pull requests merged in 2018-09, with the labels that each got.

#31 standard simple.utilities.Math module with documentation
  examples/modules/mathdemo.sim
  modules/dynamic_modules/mathic/mathic.c
  modules/dynamic_modules/mathic/mathic.h
  modules/module-map.ako
  modules/simple/utilities/Math.sim
Labels: enhancement, module

#33 Document modules
  modules/module-map.ako
  modules/simple/core/List.sim
  modules/simple/core/Number.sim
  modules/simple/utilities/Math.sim
Labels: module

#34 FEATURE : implements calling file by module name e.g simple.core.String
  ROADMAP.MD
  environment/simplerepl/simplerepl.sim
  examples/basic/callfeature.sim
  examples/modules/consoledemo.sim
  examples/modules/mathdemo.sim
  modules/dynamic_modules/consoler/consoler.c
  modules/dynamic_modules/consoler/consoler.h
  modules/module-map.ako
  modules/simple/core/List.sim
  modules/simple/system/System.sim
  modules/simple/utilities/Console.sim
  modules/web/front/Webpage.sim
  modules/web/functions/Methods.sim
  simple/includes/simple_parser.h
  simple/sources/simple_parser.c
  simple/sources/simple_stmt.c
Labels: enhancement
